### ISSUE TITLE
"What to watch out for" - install() command

### ISSUE THREAD

**Issue by dhern023** [bewagner/fetchContent_example#1]
Hi,

I have this [library](https://github.com/dhern023/linear_algebra) that just contains headers & cpp files I want to include in my [project](https://github.com/dhern023/ScientificComputingWCpp). 

I'm following your blog post on this and I'm asking: what minimum install() commands does the dependency need for FetchContent to work? 

I simply get
```
fatal error: couts.h: No such file or directory
    2 | #include "couts.h"
```
and I've tried `#include "linear_algebra/couts.h"` and `#include <linear_algebra/couts.h>` to no avail.

Thanks

**Comment by bewagner** [comment]
Hi, I just build your project and I could include the `linear_algebra` library without any modifications to the CMakelists.txt.
In the documentation, I couldn't find what exactly one has to specify. But you supplied everything FetchContent needs.

**Comment by dhern023** [comment]
Hi Bert, thanks for checking up. It turns out I was missing the last line in my parent project

```cmake
# your example stopped here
target_link_libraries(${PROJECT_NAME} linear_algebra) # add other fetched names here
# line I was missing
target_include_directories(${PROJECT_NAME} PUBLIC ${linear_algebra_SOURCE_DIR})
```

Cheers
